### ISSUE TITLE
sqlite3.OperationalError: Could not decode to UTF-8 column 'content' with text

### ISSUE THREAD

**Issue by puzzle9** [ppwwyyxx/wechat-dump#100]
```
[00:00:38 79@parser.py:wechat.parser] Your username is: xxx
[00:00:38 53@parser.py:wechat.parser] Found 2636 names in `contact` table.
[00:00:38 43@msg.py:wechat.msg] Unhandled message type: 285212721
[00:00:38 43@msg.py:wechat.msg] Unhandled message type: 318767153
[00:00:38 43@msg.py:wechat.msg] Unhandled message type: 10002
[00:00:38 43@msg.py:wechat.msg] Unhandled message type: 570425393
[00:00:38 43@msg.py:wechat.msg] Unhandled message type: 469762097
[00:00:39 43@msg.py:wechat.msg] Unhandled message type: 64
[00:00:39 43@msg.py:wechat.msg] Unhandled message type: 536870961
Traceback (most recent call last):
  File "/vhost/test/wec/wechat-dump/./list-chats.py", line 14, in <module>
    parser = WeChatDBParser(db_file)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/vhost/test/wec/wechat-dump/wechat/parser.py", line 37, in __init__
    self._parse()
  File "/vhost/test/wec/wechat-dump/wechat/parser.py", line 119, in _parse
    self._parse_msg()
  File "/vhost/test/wec/wechat-dump/wechat/parser.py", line 61, in _parse_msg
    for row in db_msgs:
               ^^^^^^^
sqlite3.OperationalError: Could not decode to UTF-8 column 'content' with text '������������������������������������������������������������������������������������������������������������������������������������������������
```

How can I provide more information

**Comment by ppwwyyxx** [comment]
Fixed in https://github.com/ppwwyyxx/wechat-dump/commit/89809d4df57dc5fdd16154ac95526506e69b3175
