### ISSUE TITLE
dump-msg.py failed due to a deleted chatroom

### ISSUE THREAD

**Issue by pymito** [ppwwyyxx/wechat-dump#17]
./dump-msg.py decrypted.db rawMsg
[23:20:40 75@parser.py:wechat.parser] Your username is: wxid_x
[23:20:40 49@parser.py:wechat.parser] Found x contacts.
[23:20:40 47@msg.py:wechat.msg] Unhandled message type: x
Traceback (most recent call last):
  File "./dump-msg.py", line 23, in <module>
    parser = WeChatDBParser(db_file)
  File "wechat-dump-master/wechat/parser.py", line 35, in __init__
    self._parse()
  File "wechat-dump-master/wechat/parser.py", line 113, in _parse
    self._parse_msg()
  File "wechat-dump-master/wechat/parser.py", line 64, in _parse_msg
    for k, v in self.msgs_by_talker.iteritems()}
  File "wechat-dump-master/wechat/parser.py", line 64, in <dictcomp>
    for k, v in self.msgs_by_talker.iteritems()}
KeyError: u'x@chatroom'

=======================
Just FYI, x@chatroom is a deleted chatroom.

**Comment by ppwwyyxx** [comment]
Thanks! Looks like messages will remain in database after deleting the chatroom.
I added a quick fix.

**Comment by pymito** [comment]
Thanks! Nice works!

**Comment by ppwwyyxx** [comment]
closed with commit 2990f364834d814ab2fb
