### ISSUE TITLE
sqlite3.OperationalError: no such column: cdnUrl

### ISSUE THREAD

**Issue by weakish** [ppwwyyxx/wechat-dump#30]
```sh
; ./list-chats.py decrypted.db
[parser.py:wechat.parser] Your username is: wxid_****
[parser.py:wechat.parser] Found ** contacts.
[msg.py:wechat.msg] Unhandled message type: 285212721
[msg.py:wechat.msg] Unhandled message type: 35
[msg.py:wechat.msg] Unhandled message type: 268435505
[parser.py:wechat.parser] Found ** message records.
[parser.py:wechat.parser] Found ** hd image records.
Traceback (most recent call last):
  File "./list-chats.py", line 14, in <module>
    parser = WeChatDBParser(db_file)
  File "/pool/repos/contrib/wechat-dump/wechat/parser.py", line 39, in __init__
    self._parse()
  File "/pool/repos/contrib/wechat-dump/wechat/parser.py", line 122, in _parse
    self._parse_emoji()
  File "/pool/repos/contrib/wechat-dump/wechat/parser.py", line 107, in _parse_emoji
    """ SELECT md5, catalog, name, cdnUrl FROM EmojiInfo""")
sqlite3.OperationalError: no such column: cdnUrl
```

Same error with `dump-msg.py` and `dump-html.py`.

WeChat 5.2 (Too old to be compatible with current WeChat database schema?)

**Comment by ppwwyyxx** [comment]
Maybe the version is the reason. That part of code about emoji was added in this June.
If you have to work with that version, you can try to ignore those code in `_parse_emoji` and the rest part should work well. Or maybe checking out to an older commit.

**Comment by weakish** [comment]
> Maybe the version is the reason.

Confirmed. I updated WeChat to 6.3 and it works.
